### DISCUSSION TITLE
HA native integration

### DISCUSSION THREAD

**Discussion by spbrogan** [spbrogan/sensor.mopeka_pro_check#22] [General]
Seems like as of summer 2022 HA is making some breaking changes.  My limited understanding is this component may not work anymore.  I don't use this much because I use the esphome integration as it just fits my needs better (My HA device is not near sensors, so I use esp32 as a bridge to wifi).  https://esphome.io/components/sensor/mopeka_pro_check.html?highlight=mopeka 
 
Additionally, it seems like there is an effort by some to move BLE integrations into HA.  I am watching this closely and will probably follow the pattern once one is integrated and stable.  

Read the readme here:
https://github.com/custom-components/ble_monitor

And these seem like the first two integrations
https://github.com/home-assistant/core/pull/75594
https://github.com/home-assistant/core/pull/75531

Anyway, no timeline yet but just wanted to provide roadmap information for anyone interested.   If you have any feedback feel free to use this discussion thread.  

Thanks

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/86500

I only have the pro plus model and not the check model.

Thanks for writing the lib, it was helpful for figuring out how to support the check as well and for the some of the data conversion.

If you get a chance to test it, it would be nice to know if I got anything obvious wrong:
https://github.com/Bluetooth-Devices/mopeka-iot-ble/blob/main/src/mopeka_iot_ble/parser.py

**Reply by spbrogan** [reply]
@bdraco - Great to see.  A few questions and comments. I'll test it out once this goes to a HA beta release and then archive this repo.  

1. would it be easy to only do the new device flow for a device which has the "sync" button pressed.  This means when at an RV campground you will not have everyone's sensor showing up on your HA.  The workflow to add new sensor would be to press the button and then HA would see the device and detect that is a mopeka device.  
2. Do you have suggestions for easily converting to tank %.  Given this is generally attached to a few standard tank sizes it is nice to know a %.  Would some sort of HA template sensor be more appropriate?  I have had a number of people concerned that % didn't match the app so there was work that went into figuring out exactly which max/min numbers the app uses to then convert to tank %.  
3. The temperature value hasn't worked out to be very interesting.  It is always running hot because it is on the sensor board.  Mopeka mentions that it isn't calibrated for "outside" temp.  Anyway, might want to hide that sensor by default and have docs that mention it shouldn't really be used as reliable source of outside temp. 
4. I also have created this integration into esphome.  In that integration there has been yet another sensor type added.  Mopeka seems to ODM devices for a few other brands and they change the sensor type so that you must use the app matching the brand.  You might want to include that here too.  https://github.com/esphome/esphome/pull/4118

**Reply by bdraco** [reply]
> 1. would it be easy to only do the new device flow for a device which has the "sync" button pressed.  This means when at an RV campground you will not have everyone's sensor showing up on your HA.  The workflow to add new sensor would be to press the button and then HA would see the device and detect that is a mopeka device.

I think it would be hard to access the pro plus devices after install on a large tank so I'd prefer not use HA's standard method of ignoring discoveries that are undesired instead.  If there are too many discoveries that is a broader problem with HA that should be addressed with a frontend change.

> 2. Do you have suggestions for easily converting to tank %.  Given this is generally attached to a few standard tank sizes it is nice to know a %.  Would some sort of HA template sensor be more appropriate?  I have had a number of people concerned that % didn't match the app so there was work that went into figuring out exactly which max/min numbers the app uses to then convert to tank %.

I think a template sensor would be the best bet for this.  

> 3. The temperature value hasn't worked out to be very interesting.  It is always running hot because it is on the sensor board.  Mopeka mentions that it isn't calibrated for "outside" temp.  Anyway, might want to hide that sensor by default and have docs that mention it shouldn't really be used as reliable source of outside temp.

At least for the Pro Plus sensor, it seemed very accurate.

> 4. I also have created this integration into esphome.  In that integration there has been yet another sensor type added.  Mopeka seems to ODM devices for a few other brands and they change the sensor type so that you must use the app matching the brand.  You might want to include that here too.  [Add support for Lippert LP sensors in mopeka_pro_check component esphome/esphome#4118](https://github.com/esphome/esphome/pull/4118)

I ordered the Lippert sensor. I'll add a virtual integration for it and add it to discovery once it shows up

**Reply by spbrogan** [reply]
1. Yes, i think this is a problem for non-home based deployments.  I use HA in my RV and my RV has 2 propane tank sensors and a few temp sensors.  When I drive into a campground, I now get dozens of "new devices found" and it is only getting worse with the addition of more native integrations.  

For the BLE proxy work in general, i have concerns about how much wifi noise/bandwidth it will add.  Has there been any discussion about filtering or minimizing the data sent to HA if it is a new device?

**Reply by bdraco** [reply]
> 1. Yes, i think this is a problem for non-home based deployments.  I use HA in my RV and my RV has 2 propane tank sensors and a few temp sensors.  When I drive into a campground, I now get dozens of "new devices found" and it is only getting worse with the addition of more native integrations.  
> 
> 
> 
> For the BLE proxy work in general, i have concerns about how much wifi noise/bandwidth it will add.  Has there been any discussion about filtering or minimizing the data sent to HA if it is a new device?  

There have been a few esphome PR attempts.  None have been successful

**Reply by bdraco** [reply]
> At least for the Pro Plus sensor, it seemed very accurate.

The check model showed up today. Side by side the plus was spot on and the check was might higher than the actual temp.

**Comment by jpettitt** [comment]
I have written a Shelly script to translate Mopkea BLE to MQTT 

https://github.com/ALLTERCO/shelly-script-examples/blob/main/ble-mopeka.js

It will just publish an MQTT topic for any Mopeka device it detects, no need for sync.

MQTT message
```
{
	"valid": true,
	"addr": "11:22:33:44:55:66",
	"rssi": -71,
	"data": {
		"id":  123456,
		"acceloX": -0.012695,
		"acceloY": 0,
		"tankLevel": 611,
		"rawTime": 1521,
		"quality": 3,
		"temperatureC": 15,
		"batteryVoltage": 3.468750,
		"deviceType": 8
	}
}
```

**Reply by spbrogan** [reply]
I personally use MQTT for many things but don't yet have a consistent view on when to go native, esphome, or mqtt.  I have authored this project for RVC stuff. https://github.com/spbrogan/rvc2mqtt  

If you are using mqtt for HA you might want to look at HA autodiscover so that you don't have to use yaml entries.  
Regardless, thanks for sharing.

**Comment by spbrogan** [comment]
Here is an example of a template sensor for a 30lbs vertical propane tank.   You can check out the esphome integration to see the values for empty and full.  https://github.com/esphome/esphome/blob/dev/esphome/components/mopeka_pro_check/sensor.py#L44
 

``` yaml
template:
  - sensor:
      - name: "Propane Tank: Drivers Side"
        unique_id: "template.propanetank.30lbs.3c76"
        icon: "mdi:propane-tank"
        unit_of_measurement: "%"
        state: >
          {% set tank_100 = 381.0 %}
          {% set tank_0 = 38.0 %}
          {% set v = states('sensor.pro_check_3c76_tank_level') | float %}
          {% set vf = min(100, int((100.0/(tank_100 - tank_0)) * (v - tank_0))) %}
          {{ vf }}
  - sensor:
      - name: "Propane Tank: Passenger Side"
        unique_id: "template.propanetank.30lbs.51ec"
        icon: "mdi:propane-tank"
        unit_of_measurement: "%"
        state: >
          {% set tank_100 = 381.0 %}
          {% set tank_0 = 38.0 %}
          {% set v = states('sensor.pro_check_51ec_tank_level') | float %}
          {% set vf = min(100, int((100.0/(tank_100 - tank_0)) * (v - tank_0))) %}
          {{ vf }}
```

Feedback welcome.
