### ISSUE TITLE
Error "Exception: 8 is not a valid HardwareId"

### ISSUE THREAD

**Issue by jpettitt** [spbrogan/sensor.mopeka_pro_check#31]
I just installed a Mopeka PRO+ LR sensor and I'm getting an error

`ERROR (HCISocketPoller) [mopeka_pro_check.service] Failed to process advertisement from defined sensor.  Exception: 8 is not a valid HardwareId` 

Config is:

```
sensor:
  - platform: mopeka_pro_check
    hci_device: "hci0"
    mopeka_devices:
      - mac: "xx:xx:xx:xx:xx:xx"
        name: "House Tank"
        tank_type: "custom"
        max_height: 760
        min_height: 38.1
```

I can't find where that message is coming from or where the hardware is checked.  any suggestions for debugging this?
